import {Button, VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";

    export component App inherits Window {
        title: "Sortout";

        in property <string> current_folder;
        in property <string> current_file;
        in property <string> current_file_type;

        in property <string> current_file_content_text;
        in property <image> current_file_content_image;

        in property <string> folder1_name;
        in property <string> folder2_name;
        in property <string> folder3_name;
        in property <string> folder4_name;
        in property <string> folder5_name;
        in property <string> folder6_name;
        in property <string> folder7_name;
        in property <string> folder8_name;
        in property <string> folder9_name;
        in property <string> folder10_name;
        in property <string> folder11_name;
        in property <string> folder12_name;

        in property <string> marked_deletion_list;
        in property <string> marked_f1_list;
        in property <string> marked_f2_list;
        in property <string> marked_f3_list;
        in property <string> marked_f4_list;
        in property <string> marked_f5_list;
        in property <string> marked_f6_list;
        in property <string> marked_f7_list;
        in property <string> marked_f8_list;
        in property <string> marked_f9_list;
        in property <string> marked_f10_list;
        in property <string> marked_f11_list;
        in property <string> marked_f12_list;

        in property <bool> folder_chosen;
        in property <bool> folder_opened;

        callback choose_folder <=> choose_folder_btn.clicked;
        callback open_folder <=> open_folder_btn.clicked;

        callback prev_file <=> previous_file_btn.clicked;
        callback next_file <=> next_file_btn.clicked;

        callback mark_delete <=> mark_delete_btn.clicked;

        callback confirm_marks <=> confirm_marks_btn.clicked;

        VerticalBox {
            Text { text : "Current folder: " + current_folder; }

            choose_folder_btn := Button { text: "Choose folder"; }

            open_folder_btn := Button { text: "Open folder"; enabled: folder_chosen; }

            HorizontalBox {
                alignment: space-between;

                VerticalBox {
                    width: 7%;
                    Text { text: "Marked for deletion:"; }
                    Text { text: marked_deletion_list; }
                }
                VerticalBox {
                    width: 7%;
                    Text { text: "Marked for folder:"; }
                    Text { text: folder1_name; }
                    Text { text: marked_f1_list; }
                }
            }

            confirm_marks_btn := Button { text: "Confirm marks"; enabled: folder_opened; }

            VerticalBox {
                Text { text : "Current file"; }
                Text { text : "File name: " + current_file; }
                Text { text: "File type: " + current_file_type; }
                Text { text: "File contents: "; }
                Text { text: current_file_content_text;}
                Image { source: current_file_content_image; width: 60%; height: 60%; image-rendering: pixelated;}
            }

            HorizontalBox {
                alignment: space-between;

                mark_delete_btn := Button { text: "Delete"; enabled: folder_opened; width: 7%;}
                mark_move_f1_btn := Button { text: "Folder 1"; width: 7%;}
                mark_move_f2_btn := Button { text: "Folder 2"; width: 7%;}
                mark_move_f3_btn := Button { text: "Folder 3"; width: 7%;}
                mark_move_f4_btn := Button { text: "Folder 4"; width: 7%;}
                mark_move_f5_btn := Button { text: "Folder 5"; width: 7%;}
                mark_move_f6_btn := Button { text: "Folder 6"; width: 7%;}
                mark_move_f7_btn := Button { text: "Folder 7"; width: 7%;}
                mark_move_f8_btn := Button { text: "Folder 8"; width: 7%;}
                mark_move_f9_btn := Button { text: "Folder 9"; width: 7%;}
                mark_move_f10_btn := Button { text: "Folder 10"; width: 7%;}
                mark_move_f11_btn := Button { text: "Folder 11"; width: 7%;}
                mark_move_f12_btn := Button { text: "Folder 12"; width: 7%;}
            }

            HorizontalBox {
                previous_file_btn := Button { text: "<"; enabled: folder_opened; }

                next_file_btn := Button { text: ">"; enabled: folder_opened; }
            }
        }


        forward-focus: my-key-handler;

        my-key-handler := FocusScope {
            key-pressed(event) => {
                if event.text == Key.LeftArrow { previous_file_btn.clicked(); }
                if event.text == Key.RightArrow { next_file_btn.clicked(); }
                if event.text == Key.Delete { mark_delete_btn.clicked(); }
                if event.text == Key.F1 { mark_move_f1_btn.clicked(); }
                if event.text == Key.F2 { mark_move_f2_btn.clicked(); }
                if event.text == Key.F3 { mark_move_f3_btn.clicked(); }
                if event.text == Key.F4 { mark_move_f4_btn.clicked(); }
                if event.text == Key.F5 { mark_move_f5_btn.clicked(); }
                if event.text == Key.F6 { mark_move_f6_btn.clicked(); }
                if event.text == Key.F7 { mark_move_f7_btn.clicked(); }
                if event.text == Key.F8 { mark_move_f8_btn.clicked(); }
                if event.text == Key.F9 { mark_move_f9_btn.clicked(); }
                if event.text == Key.F10 { mark_move_f10_btn.clicked(); }
                if event.text == Key.F11 { mark_move_f11_btn.clicked(); }
                if event.text == Key.F12 { mark_move_f12_btn.clicked(); }

                accept
            }
    }
    }